-- Create the proposals table
create table if not exists public.proposals (
    id bigint generated by default as identity primary key,
    title text not null,
    client text not null,
    value text, -- Using text for formatting like 'R$ 5.000'
    status text check (status in ('Rascunho', 'Enviada', 'Aprovada', 'Rejeitada')) default 'Rascunho',
    date date default current_date,
    valid_until date,
    items jsonb default '[]'::jsonb,
    context jsonb,
    solution jsonb,
    scope jsonb,  -- Array of strings
    schedule jsonb, -- Array of objects {week, task}
    payment_terms text,
    next_steps text,
    share_token text unique,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.proposals enable row level security;

-- Policy to allow authenticated users (admin) to perform all actions
create policy "Allow all actions for authenticated users" 
on public.proposals 
for all 
to authenticated 
using (true) 
with check (true);

-- Policy to allow public read access (for shareable links)
-- In a stricter environment, this should check for the presence of the share_token in the query or similar mechanism.
-- For simplicity and sharing:
create policy "Allow public read access" 
on public.proposals 
for select 
to anon 
using (true);

-- Grant usage on sequence for id generation (if needed, usually handled by identity)
grant all on table public.proposals to authenticated;
grant select on table public.proposals to anon;
